config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :todolists
  root 'todolists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todolist.rb
class Todolist < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
	before_action :find_todolist, only: [:edit, :update, :delete]

	def index
		@todolists = Todolist.all
	end

	def new
		@todolist = Todolist.new
	end

	def create
		@todolist = Todolist.new(todolist_params)
		if @todolist.save
			redirect_to todolists_path, notice: "新增待辦事項完成"
		else
			render new
		end
	end

	def edit

	end

	def update
		if @todolist.update(todolist_params)
			redirect_to todolists_path, notice: "更新完成"
		else
			render :edit
		end
	end

	def destroy
		@todolist = Todolist.find_by(id: params[:id])
		@todolist.destroy
		redirect_to todolists_path, notice: "待辦事項已刪除"
	end

	private
	  def find_todolist
	  	@todolist = Todolist.find_by(id: params[:id])
	  	redirect_to todolists_path, notice: "並無此待辦事項" if not @todolist
	  end

	  def todolist_params
	  	params.require(:todolist).permit(:title, :description)
	  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTodolist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
  		<%= notice %>
	    <%= yield %>
    </div>
  </body>
</html>

app/views/todolists/_form.html.erb
<%= simple_form_for todolist do |f| %>
	<%= f.input :title, placeholder: "名稱" %>
	<%= f.input :description, placeholder: "請輸入描述" %>
	<%= f.submit class: "btn btn-default btn-primary" %>
<% end %>

app/views/todolists/edit.html.erb
<h1>Edit TodoList</h1>


<%= render "form", todolist: @todolist %>
<br>
<div class="btn btn=default btn-info"><%= link_to "Back", todolists_path %></div>

app/views/todolists/index.html.erb
<h1>todolist</h1>

<%= link_to "新增待辦事項", new_todolist_path, class: "btn btn-success"  %>

<table class="table table-striped">
	<thead>
		<tr>
			<th>名稱</th>
			<th>描述</th>
			<th>功能</th>
		</tr>
	</thead>
	<tbody>
		<% @todolists.each do |todolist| %>
		<tr>
			<td><%= todolist.title %></td>
			<td><%= todolist.description %></td>
			<td>
				<%= link_to "編輯", edit_todolist_path(todolist), class: "btn btn-xs btn-primary" %>
				<%= link_to "刪除", todolist, method: "delete", data: { confirm: "確定刪除？" }, class: "btn btn-xs btn-danger" %>			
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/todolists/new.html.erb
<h1>New TodoList</h1>


<%= render "form", todolist: @todolist %>
<br>
<div class="btn btn=default btn-info"><%= link_to "Back", todolists_path %></div>